package store

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

func bytesReader(b []byte) *bytes.Reader { return bytes.NewReader(b) }

// openTestDB opens a database rooted in a throwaway data dir.
func openTestDB(t *testing.T) (*DB, string) {
	t.Helper()
	dir := t.TempDir()
	db, err := Open(filepath.Join(dir, "launcher.db"), dir)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	t.Cleanup(func() { db.Close() })
	return db, dir
}

// TestAuditHashCompat verifies Go recomputes the exact hashes the Python
// implementation produced. The fixture file is generated by
// scripts/dev/gen_audit_fixtures.py, which runs the real Python hasher.
func TestAuditHashCompat(t *testing.T) {
	raw, err := os.ReadFile("testdata/audit_hash_fixtures.json")
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}
	var entries []map[string]any
	dec := json.NewDecoder(bytesReader(raw))
	dec.UseNumber()
	if err := dec.Decode(&entries); err != nil {
		t.Fatalf("decode fixtures: %v", err)
	}
	for _, entry := range entries {
		want := asString(entry["_hash"])
		got := HashEntry(entry)
		if got != want {
			t.Errorf("hash mismatch for id %v:\n got  %s\n want %s", entry["id"], got, want)
		}
	}
}

// TestHashStableAcrossRoundTrip checks that hashing an entry, storing it
// and re-reading it produces the same hash: numbers must survive the
// round trip without being reformatted.
func TestHashStableAcrossRoundTrip(t *testing.T) {
	entry := map[string]any{
		"id":        "x1",
		"timestamp": 1759234567.89,
		"action":    "updated",
		"count":     3,
		"ratio":     0.5,
		"big":       1234567890123.456,
		"unicode":   "héllo",
	}
	first := HashEntry(entry)
	roundTripped := Normalize(entry).(map[string]any)
	second := HashEntry(roundTripped)
	if first != second {
		t.Errorf("hash changed across round trip:\n first  %s\n second %s", first, second)
	}
}

func TestLoadSaveRoundTrip(t *testing.T) {
	db, _ := openTestDB(t)
	in := []map[string]any{
		{"id": "p1", "name": "First", "timeout": 2.5, "args": []any{"--x", "1"}},
		{"id": "p2", "name": "Sécond", "enabled": true, "nested": map[string]any{"deep": []any{1, 2}}},
	}
	if err := db.Save("profiles", in); err != nil {
		t.Fatalf("Save: %v", err)
	}
	out, err := db.Load("profiles")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(out) != 2 {
		t.Fatalf("got %d items, want 2", len(out))
	}
	if asString(out[0]["name"]) != "First" || asString(out[1]["name"]) != "Sécond" {
		t.Errorf("order not preserved: %v %v", out[0]["name"], out[1]["name"])
	}
	if fmt.Sprint(out[0]["timeout"]) != "2.5" {
		t.Errorf("number literal not preserved: %v (%T)", out[0]["timeout"], out[0]["timeout"])
	}
}

// TestSavePreservesInsertOrderOnReload is the ordering contract the
// drag-to-reorder UI relies on: the last Save order is the Load order.
func TestSavePreservesInsertOrderOnReload(t *testing.T) {
	db, _ := openTestDB(t)
	items := []map[string]any{}
	for i := 0; i < 5; i++ {
		items = append(items, map[string]any{"id": fmt.Sprintf("p%d", i), "name": fmt.Sprintf("Item %d", i)})
	}
	if err := db.Save("profiles", items); err != nil {
		t.Fatalf("Save: %v", err)
	}
	// Reorder: move the last item to the front.
	reordered := []map[string]any{items[4], items[0], items[1], items[2], items[3]}
	if err := db.Save("profiles", reordered); err != nil {
		t.Fatalf("Save reorder: %v", err)
	}
	out, _ := db.Load("profiles")
	for i, want := range []string{"p4", "p0", "p1", "p2", "p3"} {
		if asString(out[i]["id"]) != want {
			t.Errorf("position %d: got %v want %s", i, out[i]["id"], want)
		}
	}
}

// TestSaveAssignsMissingIDs covers save_json's behaviour of giving new
// random hex ids to items that lack one.
func TestSaveAssignsMissingIDs(t *testing.T) {
	db, _ := openTestDB(t)
	if err := db.Save("profiles", []map[string]any{{"name": "No id"}}); err != nil {
		t.Fatalf("Save: %v", err)
	}
	out, _ := db.Load("profiles")
	if len(out) != 1 || asString(out[0]["id"]) == "" {
		t.Fatalf("expected an assigned id, got %v", out)
	}
	if len(asString(out[0]["id"])) != 32 {
		t.Errorf("id should be 32 hex chars, got %q", out[0]["id"])
	}
}

// TestLegacyJSONMigration mirrors the Python behaviour: on first open,
// a profiles.json left by an old version is imported into the table.
func TestLegacyJSONMigration(t *testing.T) {
	dir := t.TempDir()
	legacy := `[{"id": "old1", "name": "Legacy"}, {"name": "No id legacy"}]`
	if err := os.WriteFile(filepath.Join(dir, "profiles.json"), []byte(legacy), 0o644); err != nil {
		t.Fatal(err)
	}
	db, err := Open(filepath.Join(dir, "launcher.db"), dir)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer db.Close()
	out, err := db.Load("profiles")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(out) != 2 {
		t.Fatalf("got %d records, want 2", len(out))
	}
	if asString(out[0]["id"]) != "old1" || asString(out[1]["id"]) == "" {
		t.Errorf("migration content wrong: %v", out)
	}
}

// TestRecordAuditAndVerify runs the write-then-verify path end to end.
func TestRecordAuditAndVerify(t *testing.T) {
	db, _ := openTestDB(t)
	db.RecordAudit("created", "profile", "p1", "Test", nil,
		map[string]any{"name": "Test"}, map[string]any{"duplicate_of": "orig"})
	ok, tampered := db.VerifyAuditIntegrity()
	if !ok || len(tampered) != 0 {
		t.Fatalf("fresh audit trail should verify: ok=%v tampered=%v", ok, tampered)
	}

	// Tamper with the stored entry, then reload: verification must fail
	// for exactly that entry.
	entries, _ := db.Load("audit")
	entries[0]["action"] = "tampered"
	if err := db.Save("audit", entries); err != nil {
		t.Fatal(err)
	}
	ok, tampered = db.VerifyAuditIntegrity()
	if ok || len(tampered) != 1 || tampered[0] != asString(entries[0]["id"]) {
		t.Fatalf("tampering should be detected: ok=%v tampered=%v", ok, tampered)
	}
}

// TestAuditTrimToMax checks the 1000-entry cap.
func TestAuditTrimToMax(t *testing.T) {
	db, _ := openTestDB(t)
	for i := 0; i < AuditMax + 3; i++ {
		db.RecordAudit("updated", "profile", "p", fmt.Sprintf("n%d", i), nil, nil, nil)
	}
	entries, _ := db.Load("audit")
	if len(entries) != AuditMax {
		t.Fatalf("got %d audit entries, want %d", len(entries), AuditMax)
	}
	if asString(entries[len(entries)-1]["name"]) != "n1002" {
		t.Errorf("oldest entries should have been trimmed")
	}
}

// TestChangedFields mirrors storage.changed_fields: sorted names of the
// top-level fields that differ, nil when there is no before state.
func TestChangedFields(t *testing.T) {
	before := map[string]any{"a": 1, "b": "x", "c": true}
	after := map[string]any{"a": 1, "b": "y", "d": nil}
	got := ChangedFields(before, after)
	if len(got) != 2 || got[0] != "b" || got[1] != "c" {
		t.Errorf("got %v, want [b c]", got)
	}
	if ChangedFields(nil, after) != nil {
		t.Errorf("no before state should yield nil")
	}
	if got := ChangedFields(before, before); len(got) != 0 {
		t.Errorf("identical states should yield empty, got %v", got)
	}
}

// TestUnknownCollectionIsRejected guards against typos mapping to
// surprise tables.
func TestUnknownCollectionIsRejected(t *testing.T) {
	db, _ := openTestDB(t)
	if _, err := db.Load("nope"); err == nil {
		t.Fatal("Load of unknown collection should fail")
	}
	if err := db.Save("nope", nil); err == nil {
		t.Fatal("Save of unknown collection should fail")
	}
}

// TestConcurrentSavesDoNotLoseData exercises the collection lock: two
// goroutines appending different items under the lock must both land.
func TestConcurrentSavesDoNotLoseData(t *testing.T) {
	db, _ := openTestDB(t)
	done := make(chan struct{})
	for i := 0; i < 2; i++ {
		go func(i int) {
			defer func() { done <- struct{}{} }()
			for j := 0; j < 10; j++ {
				db.WithCollection("profiles", func() {
					items, _ := db.Load("profiles")
					items = append(items, map[string]any{"name": fmt.Sprintf("g%d-%d", i, j)})
					db.Save("profiles", items)
				})
			}
		}(i)
	}
	<-done
	<-done
	out, _ := db.Load("profiles")
	if len(out) != 20 {
		t.Fatalf("got %d items, want 20 (lost writes?)", len(out))
	}
}
